name: my_crypto_info
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  sqflite: ^2.0.2
  http: ^0.13.4
  toast: 0.1.5
  device_info: ^2.0.2
  package_info: ^2.0.2
  cached_network_image: ^2.5.1
  shared_preferences: ^2.0.8
  rxdart: ^0.25.0
  html: ^0.14.0+3
  flutter_html: ^1.0.2
  flutter_phoenix: ^1.0.0
  intl:
  material_design_icons_flutter: ^5.0.6295
  html_unescape: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  progress_dialog: ^1.2.4
  data_connection_checker: ^0.3.4
  smart_select: ^4.3.2
  dio: ^4.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  pubspec_lock: ^3.0.1
  archive: ^3.2.0
  args: ^2.0.3
  yaml: ^3.1.0
  url_launcher: ^6.0.12
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: "ic_launcher"
#   adaptive_icon_background: "#ffffff"
#   adaptive_icon_foreground: "assets/icon/icon.png"
#   ios: true
#   image_path: "assets/icon/icon.png"

flutter_launcher_name:
  name: "CryptoInfo"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #assets:
  #   - assets/image/splash.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages